### PR TITLE
Add Snowpack to build and enable full TypeScript strict mode

### PR DESCRIPTION
**Pull request by lukastaegert**
I was very disappointed with the fact that we had no types for React and were therefore not able to enable full TypeScript strict mode.

By adding [SnowPack](https://www.snowpack.dev/) (which is definitely hot shit)
- we can import all node_modules dependencies via /web_modules
- they are pre-bundled for more efficiency
- we can have CJS dependencies that are converted to ESM for us
- it is finally possible to add actual types by using TypeScript "paths"

### CODE REVIEW

**Comment by lukastaegert** [comment]
I will fix our test setup... :) Will take a moment, though

**Comment by lukastaegert** [comment]
@andreashille I fixed the test setup, moved it from babel-jest to ts-jest and prepared it for using react testing library, please have another look.

**Comment by siskavera** [comment]
On my machine, it can't even be installed. `npm ci` complains that the lock file is out of date and `npm install` failes with
`npm ERR! Invalid dependency type requested: alias`

**Comment by siskavera** [comment]
On my machine (Linux) `npm ci` and `npm install` both fail.

`npm ci` complains that the lock file is out of date.

`npm install` fails with `npm ERR! Invalid dependency type requested: alias`

**Pull request merged**
