### PR TITLE
Bar chart

### PR DESCRIPTION
**Pull request by ThiloAschebrock**
This PR replaces the pie chart with a bar chart.

### CODE REVIEW

**Review by andreashille — COMMENTED** [review]
would it make sense to limit the chart to only voted values
(asume a voting of 5, 12, 20, instead showing 1-100 we show only 5-20)
also is it worth to remove the grid and instead show the ammout above or below to maintain the clean look and feel?

otherwise nice :-)

**Comment by ThiloAschebrock** [comment]
> would it make sense to limit the chart to only voted values (asume a voting of 5, 12, 20, instead showing 1-100 we show only 5-20) also is it worth to remove the grid and instead show the ammout above or below to maintain the clean look and feel?
> 
> otherwise nice :-)

I implemented your suggestion to only show the relevant values for a vote that does not spread in [9bc36ee](https://github.com/TNG/next-generation-scrum-poker/pull/120/commits/9bc36ee1fe63d4c70061d8a57cccc0be0163dad2).

I tried your suggestion of removing the grid, but it didn't feel good to me since it impairs readability of a bar char.

**Review by lukastaegert — COMMENTED** [review]
I think I like it in general. One point that does not look right to me aesthetically is that the grid uses a font size/weight combination that does not seem to occur another time on the page. Not sure how much possibility there is to influence this, though.

Another point I had not checked before is that `chart.js` massively blows up the bundle size, from 40kB to 200kB. I do not like that too much. At the very least, this should be lazy-loaded. Otherwise, not sure if there are less heavy options?
You can also inspect bundle impact by running `npx vite-bundle-visualizer` from the `frontend` directory.

**Comment by ThiloAschebrock** [comment]
> I think I like it in general. One point that does not look right to me aesthetically is that the grid uses a font size/weight combination that does not seem to occur another time on the page. Not sure how much possibility there is to influence this, though.
> 
> Another point I had not checked before is that `chart.js` massively blows up the bundle size, from 40kB to 200kB. I do not like that too much. At the very least, this should be lazy-loaded. Otherwise, not sure if there are less heavy options? You can also inspect bundle impact by running `npx vite-bundle-visualizer` from the `frontend` directory.

These are all valid points. To address them
- I switched from chartjs to chartist, which itself only has a bundle size of about 20KB. This libraries also integrates better into our style than chartjs.
- I split the bar chart component from the main bundle by lazy loading it:
```
dist/index.html                     0.74 kB │ gzip:  0.40 kB
dist/assets/tng-0bbe2c2f.svg        6.31 kB │ gzip:  2.53 kB
dist/assets/BarChart-c2df8d75.css   0.06 kB │ gzip:  0.07 kB
dist/assets/index-c80f2983.css      9.44 kB │ gzip:  2.43 kB
dist/assets/BarChart-d5203dcd.js   25.01 kB │ gzip:  8.43 kB
dist/assets/index-2dc98df0.js      46.90 kB │ gzip: 18.66 kB
```

**Review by andreashille — APPROVED** [review]

**Pull request merged**
